apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xlights-render-cache
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs  # adjust to match your NFS storage class name
  resources:
    requests:
      storage: 100Mi
