apiVersion: v1
kind: Secret
metadata:
  name: xlights-render-config
  namespace: default
type: Opaque
stringData:
  greglights_config.json: |
    {
      "host": "YOUR_MQTT_HOST",
      "port": 1883,
      "username": "YOUR_USERNAME",
      "password": "YOUR_PASSWORD"
    }
