apiVersion: v1
kind: Secret
metadata:
  name: xlights-render-config
  namespace: default
type: Opaque
stringData:
  greglights_config.json: |
    {
      "host": "YOUR_MQTT_HOST",
      "port": 1883,
      "username": "YOUR_USERNAME",
      "password": "YOUR_PASSWORD",
      "fpp_ips": ["YOUR_FPP_IP_1", "YOUR_FPP_IP_2"],
      "base_names": [
        "JEFF", "BRADY", "MARY", "NANCY", "JERRY", "HENERY",
        "ALEX", "TIM", "ABBIE", "MELISSA", "JUDY", "BRODY",
        "EMILY", "MATT", "WILL", "JULIA", "SOPHIE", "LONDON",
        "MAX", "BENNY", "LUIS", "KORIE"
      ]
    }
